apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "devex-test30"
  description: "devex-test30"
  labels:
    system: web-apps
  links:
    - url: https://github.com/RohanAwasthi/deves-test30
      title: "devex-test30"
      icon: code
  tags:
    - java
    - azure
    - applicationtype-webapplication
  annotations:
    jenkins.io/github-folder: 'apache-azure-app/devex-test30'
    jenkins.io/job-full-name: 'apache-azure-app/devex-test30'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  RohanAwasthi/deves-test30
    backstage.io/linguist: https://github.com/RohanAwasthi/deves-test30
    azure.com/tag-selector: 'pid/devex-test30'
spec:
  type: service
  lifecycle: development
  owner: group:default/manager
